### 회원가입 ( 고객 )
POST http://localhost:8081/signup/customer
Content-Type: application/json

{
  "birth": "2022-10-05",
  "email": "onlee1425@naver.com",
  "name": "string",
  "password": "string",
  "phone": "string"
}

### 이메일 인증 ( 고객 )
GET http://localhost:8081/signup/customer/verify?email=onlee1425@naver.com&code=bhtnhzpzYA


### 로그인 ( 고객 )
POST http://localhost:8081/signin/customer
Content-Type: application/json

{
  "email": "onlee1425@naver.com",
  "password": "string"
}

### 회원 정보 조회 ( 고객 )
GET http://localhost:8081/customer/getInfo
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuTXh6T2p3WStaTFBZdWJNMXc3ajJmNmtVTTduckxyL3JybWNZdWMxYXNVPSIsImp0aSI6InVXRzlXUTdFODdBTHRCaTliRVl0UWc9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2NjQ5MDIwMzYsImV4cCI6MTY2NDk4ODQzNn0.Q5XlTg8d18X3VXBbPH4x4QDYmDyzx0f3WAs3jUB9WB8

{
  "email": "onlee1425@naver.com",
  "password": "string"
}

### 잔액 변경 ( 고객 )
POST http://localhost:8081/customer/balance
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuTXh6T2p3WStaTFBZdWJNMXc3ajJmNmtVTTduckxyL3JybWNZdWMxYXNVPSIsImp0aSI6InhoTDJMQWtHMjVyenk2dlNab2xleGc9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2NjYxODM1ODksImV4cCI6MTY2NjI2OTk4OX0.bKBQ-s_XoaRP28exo6dj3qhNqAyHwkUrQIw_Jgi5OxI

{
  "from": "admin",
  "message": "충전",
  "money": 100000
}

##############################

### 회원가입 ( 셀러 )
POST http://localhost:8081/signup/seller
Content-Type: application/json

{
  "birth": "2022-10-05",
  "email": "onlee1425@naver.com",
  "name": "string",
  "password": "string",
  "phone": "string"
}

### 이메일 인증 ( 셀러 )
GET http://localhost:8081/signup/seller/verify?email=onlee1425@naver.com&code=9MJ0LLovVd


### 로그인 ( 셀러 )
POST http://localhost:8081/signin/seller
Content-Type: application/json

{
  "email": "onlee1425@naver.com",
  "password": "string"
}

### 회원 정보 조회 ( 셀러 )
GET http://localhost:8081/seller/getInfo
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuTXh6T2p3WStaTFBZdWJNMXc3ajJmNmtVTTduckxyL3JybWNZdWMxYXNVPSIsImp0aSI6InhoTDJMQWtHMjVyenk2dlNab2xleGc9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY1NTA1ODY4LCJleHAiOjE2NjU1OTIyNjh9.C8AB5SLRA-syPgPOBnlC8uwQIx4ZhpJhaIQ0G6KtfFc



  "email": "onlee1425@naver.com",
  "password": "string"
}


