### 상품 추가
POST http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuTXh6T2p3WStaTFBZdWJNMXc3ajJmNmtVTTduckxyL3JybWNZdWMxYXNVPSIsImp0aSI6InhoTDJMQWtHMjVyenk2dlNab2xleGc9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY1NTA1ODY4LCJleHAiOjE2NjU1OTIyNjh9.C8AB5SLRA-syPgPOBnlC8uwQIx4ZhpJhaIQ0G6KtfFc


{
  "description": "상품 설명",
  "items": [
    {
      "count": 1,
      "name": "270",
      "price": 10000
    }
  ],
  "name": "나이키 에어포스"
}

### 상품 내 아이템 추가
POST http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuTXh6T2p3WStaTFBZdWJNMXc3ajJmNmtVTTduckxyL3JybWNZdWMxYXNVPSIsImp0aSI6InhoTDJMQWtHMjVyenk2dlNab2xleGc9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY1NTA1ODY4LCJleHAiOjE2NjU1OTIyNjh9.C8AB5SLRA-syPgPOBnlC8uwQIx4ZhpJhaIQ0G6KtfFc

{
  "productId": 1,
  "count": 1,
  "name": "280",
  "price": 10000
}


