### 상품 추가
POST http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuTXh6T2p3WStaTFBZdWJNMXc3ajJmNmtVTTduckxyL3JybWNZdWMxYXNVPSIsImp0aSI6InhoTDJMQWtHMjVyenk2dlNab2xleGc9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY1Njc0NjEwLCJleHAiOjE2NjU3NjEwMTB9.Fq4-cV3bmENB7_zIxM2pLNgPIPJQ5eSmwDxAObb6Adc


{
  "description": "상품 설명",
  "items": [
    {
      "count": 1,
      "name": "270",
      "price": 10000
    }
  ],
  "name": "나이키 에어포스 2"
}

### 상품 내 아이템 추가
POST http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuTXh6T2p3WStaTFBZdWJNMXc3ajJmNmtVTTduckxyL3JybWNZdWMxYXNVPSIsImp0aSI6InhoTDJMQWtHMjVyenk2dlNab2xleGc9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY1Njc0NjEwLCJleHAiOjE2NjU3NjEwMTB9.Fq4-cV3bmENB7_zIxM2pLNgPIPJQ5eSmwDxAObb6Adc

{
  "productId": 1,
  "count": 1,
  "name": "280",
  "price": 10000
}


### 상품 수정
PUT http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuTXh6T2p3WStaTFBZdWJNMXc3ajJmNmtVTTduckxyL3JybWNZdWMxYXNVPSIsImp0aSI6InhoTDJMQWtHMjVyenk2dlNab2xleGc9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY1Njc0NjEwLCJleHAiOjE2NjU3NjEwMTB9.Fq4-cV3bmENB7_zIxM2pLNgPIPJQ5eSmwDxAObb6Adc


{
  "description": "상품 설명",
  "items": [
    {
      "id": 1,
      "count": 1,
      "name": "280",
      "price": 10000
    }
  ],
  "id": 1,
  "name": "나이키 에어포스 280"
}

### 아이템 수정
PUT http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuTXh6T2p3WStaTFBZdWJNMXc3ajJmNmtVTTduckxyL3JybWNZdWMxYXNVPSIsImp0aSI6InhoTDJMQWtHMjVyenk2dlNab2xleGc9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY1Njc0NjEwLCJleHAiOjE2NjU3NjEwMTB9.Fq4-cV3bmENB7_zIxM2pLNgPIPJQ5eSmwDxAObb6Adc

{
  "id": 1,
  "count": 1,
  "name": "280",
  "price": 10000
}


### 상품 삭제
DELETE http://localhost:8082/seller/product?id=1
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuTXh6T2p3WStaTFBZdWJNMXc3ajJmNmtVTTduckxyL3JybWNZdWMxYXNVPSIsImp0aSI6InhoTDJMQWtHMjVyenk2dlNab2xleGc9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY1Njc0NjEwLCJleHAiOjE2NjU3NjEwMTB9.Fq4-cV3bmENB7_zIxM2pLNgPIPJQ5eSmwDxAObb6Adc


{
  "description": "상품 설명",
  "items": [
    {
      "id": 1,
      "count": 1,
      "name": "270",
      "price": 10000
    }
  ],
  "name": "나이키 에어포스"
}

### 아이템 삭제
DELETE http://localhost:8082/seller/product/item?id=2
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuTXh6T2p3WStaTFBZdWJNMXc3ajJmNmtVTTduckxyL3JybWNZdWMxYXNVPSIsImp0aSI6InhoTDJMQWtHMjVyenk2dlNab2xleGc9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY1Njc0NjEwLCJleHAiOjE2NjU3NjEwMTB9.Fq4-cV3bmENB7_zIxM2pLNgPIPJQ5eSmwDxAObb6Adc


### 상품 검색
GET http://localhost:8082/search/product?name=나이키
Content-Type: application/json


### 상품 디테일 검색
GET http://localhost:8082/search/product/detail?productId=2
Content-Type: application/json
